### ISSUE TITLE
Provider window appears (from hidden state) after pressing Win+Shift+RightArrow

### ISSUE THREAD

**Issue by PhilVogt** [vagoel/platform-api-project-seed#14]

**Comment by PhilVogt** [comment]
Hi Varun,
this should be fixed with my latest checkin. Please have a look, let me know how you get on.
Thanks,
Phil.

**Comment by vagoel** [comment]
Thanks @PhilVogt for the fix.Its working and I will apply same into our project , will let you know in case there is any deviations.

**Comment by PhilVogt** [comment]
Excellent, I'm glad that helped.
