### ISSUE TITLE
Popup Window Position Issue

### ISSUE THREAD

**Issue by vagoel** [vagoel/platform-api-project-seed#18]
Hi Team ,

We raised a issue long time back regarding clipping of popups and your team mentioned it is a known issue and provided a workaround to open openfin window as a popup , mimicking the native html popup behaviour.

We are running into issues with the suggested approach since the location of popup is not correct when opened from different screen resolutions.

Attaching screenshot of the issue.

Steps To Reproduce -
1. Clone this repo - https://github.com/PhilVogt/openfin-platform-custom-tabs
2. Do npm install and then npm run start
3.Navigate to the app and open first link to load openfin app
4.Click on Services Icon to load services window popup
5.Move this window to external monitor and maximize the window.
6.Again Click on Services Icon to load services window popup.It will open at wrong position.

Please help.
![clipping-workaround-issue](https://user-images.githubusercontent.com/8045008/118629104-d9969500-b7ff-11eb-94cd-2cbb78838722.jpg)

**Comment by PhilVogt** [comment]
Hey Varun,
I've pushed a fix to https://github.com/PhilVogt/openfin-platform-custom-tabs. Just made a change to pick up the screenX and screenY from the mouse click event.

Let me know if you have any questions.

Thanks,
Phil.

**Comment by vagoel** [comment]
Thanks @PhilVogt . Its working.
