### ISSUE TITLE
Provider Window Reappears in freezed state when external monitor is attached

### ISSUE THREAD

**Issue by vagoel** [vagoel/platform-api-project-seed#8]

**Comment by vagoel** [comment]
Solved with Runtime v18.87.57.35

**Comment by vagoel** [comment]
@PhilVogt  This issue is resurfacing with some other predefined steps -

1. Run this sample app.
2.Click Login .
3.Immediately click Win+Shift+RightArrow key (Its a windows shortcut for moving screens from one monitor to another)
4. You will see provider window in freezed state.

**Comment by PhilVogt** [comment]
I created this as a seperate issue Varun, technically it is a different code path and needs a different fix. Please see my latest checkin and dont hesitate to ask if you need clarification on anything.
Thanks,
Phil.

**Comment by vagoel** [comment]
Closing this issue as Issue #14 is raised for tracking.
